# Customer Segmentation with RFM Analysis on FLO Retail Dataset

## Description

Stages of Project

1. Data Reading
2. Data Preperation
3. Defining RFM Metrics
4. Calculating RFM Scores
5. Segmentation with RFM Scores
6. Examining Outputs

### Story of dataset
The dataset consists of information obtained from the past shopping behavior of customers who made their last shopping both online and offline in 2020-2021.

Variables:
master_id: Unique client number
order_channel : Which channel of the shopping platform is used (Android, IOS, Desktop, Mobile, Offline)
last_order_channel : The channel where the last purchase was made
first_order_date : The date of the first purchase made by the customer
last_order_date : The date of the last purchase made by the customer
last_order_date_online : The date of the last purchase made by the customer on the online platform
last_order_date_offline : The date of the last purchase made by the customer on the offline platform
order_num_total_ever_online : The total number of purchases made by the customer on the online platform
order_num_total_ever_offline : Total number of purchases made by the customer offline
customer_value_total_ever_offline : The total price paid by the customer for offline purchases
customer_value_total_ever_online : The total price paid by the customer for their online shopping
interested_in_categories_12 : List of categories the customer has shopped in the last 12 months

## Data Preperation and Understanding

### Reading Data, Required Libraries, Settings and Functions

In [2]:
import pandas as pd
import datetime as dt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.width',1000)

In [8]:
df_ = pd.read_csv("./flo_data_20k.csv")

In [9]:
df = df_.copy()

In [24]:
def check_df(dataframe, head=5):
    print("##################### Shape #####################\n")
    print(dataframe.shape)
    print("\n##################### Types #####################\n")
    print(dataframe.dtypes)
    print("\n##################### Types #####################\n")
    print(dataframe.info())
    print("\n##################### Head #####################\n")
    print(dataframe.head(head))
    print("\n##################### Tail #####################\n")
    print(dataframe.tail(head))
    print("\n##################### MissingValues #######################\n")
    print(dataframe.isnull().sum())
    print("\n##################### Quantiles #####################\n")
    print(dataframe.quantile([0, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99, 1]).T)

In [28]:
def data_prep(dataframe):
    dataframe["order_num_total"] = dataframe["order_num_total_ever_online"] + dataframe["order_num_total_ever_offline"]
    dataframe["customer_value_total"] = dataframe["customer_value_total_ever_offline"] + dataframe["customer_value_total_ever_online"]
    date_columns = dataframe.columns[dataframe.columns.str.contains("date")]
    dataframe[date_columns] = dataframe[date_columns].apply(pd.to_datetime)
    return df

### Exploratory Data Analysis

In [25]:
check_df(df)

##################### Shape #####################

(19945, 12)

##################### Types #####################

master_id                             object
order_channel                         object
last_order_channel                    object
first_order_date                      object
last_order_date                       object
last_order_date_online                object
last_order_date_offline               object
order_num_total_ever_online          float64
order_num_total_ever_offline         float64
customer_value_total_ever_offline    float64
customer_value_total_ever_online     float64
interested_in_categories_12           object
dtype: object

##################### Types #####################

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19945 entries, 0 to 19944
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   master_id                          19945 non-null  object
 1   order_channel                      19945 non-null  object
 2   last_order_channel                 19945 non-null  object
 3   first_order_date                   19945 non-null  object
 4   last_order_date                    19945 non-null  object
 5   last_order_date_online             19945 non-null  object
 6   last_order_date_offline            19945 non-null  object
 7   order_num_total_ever_online        19945 non-null  float64
 8   order_num_total_ever_offline       19945 non-null  float64
 9   customer_value_total_ever_offline  19945 non-null  float64
 10  customer_value_total_ever_online   19945 non-null  float64
 11  interested_in_categories_12        19945 non-null  object
dtypes: float64(4), object(8)
memory usage: 1.8+ MB
None

##################### Head #####################

                              master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online       interested_in_categories_12
0  cc294636-19f0-11eb-8d74-000d3a38a36f   Android App            Offline       2020-10-30      2021-02-26             2021-02-21              2021-02-26                         4.00                          1.00                             139.99                            799.38                           [KADIN]
1  f431bd5a-ab7b-11e9-a2fc-000d3a38a36f   Android App             Mobile       2017-02-08      2021-02-16             2021-02-16              2020-01-10                        19.00                          2.00                             159.97                           1853.58  [ERKEK, COCUK, KADIN, AKTIFSPOR]
2  69b69676-1a40-11ea-941b-000d3a38a36f   Android App        Android App       2019-11-27      2020-11-27             2020-11-27              2019-12-01                         3.00                          2.00                             189.97                            395.35                    [ERKEK, KADIN]
3  1854e56c-491f-11eb-806e-000d3a38a36f   Android App        Android App       2021-01-06      2021-01-17             2021-01-17              2021-01-06                         1.00                          1.00                              39.99                             81.98               [AKTIFCOCUK, COCUK]
4  d6ea1074-f1f5-11e9-9346-000d3a38a36f       Desktop            Desktop       2019-08-03      2021-03-07             2021-03-07              2019-08-03                         1.00                          1.00                              49.99                            159.99                       [AKTIFSPOR]

##################### Tail #####################

                                  master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online interested_in_categories_12
19940  727e2b6e-ddd4-11e9-a848-000d3a38a36f   Android App            Offline       2019-09-21      2020-07-05             2020-06-05              2020-07-05                         1.00                          2.00                             289.98                            111.98          [ERKEK, AKTIFSPOR]
19941  25cd53d4-61bf-11ea-8dd8-000d3a38a36f       Desktop            Desktop       2020-03-01      2020-12-22             2020-12-22              2020-03-01                         1.00                          1.00                             150.48                            239.99                 [AKTIFSPOR]
19942  8aea4c2a-d6fc-11e9-93bc-000d3a38a36f       Ios App            Ios App       2019-09-11      2021-05-24             2021-05-24              2019-09-11                         2.00                          1.00                             139.98                            492.96                 [AKTIFSPOR]
19943  e50bb46c-ff30-11e9-a5e8-000d3a38a36f   Android App        Android App       2019-03-27      2021-02-13             2021-02-13              2021-01-08                         1.00                          5.00                             711.79                            297.98          [ERKEK, AKTIFSPOR]
19944  740998d2-b1f7-11e9-89fa-000d3a38a36f   Android App        Android App       2019-09-03      2020-06-06             2020-06-06              2019-09-03                         1.00                          1.00                              39.99                            221.98          [KADIN, AKTIFSPOR]

##################### MissingValues #######################

master_id                            0
order_channel                        0
last_order_channel                   0
first_order_date                     0
last_order_date                      0
last_order_date_online               0
last_order_date_offline              0
order_num_total_ever_online          0
order_num_total_ever_offline         0
customer_value_total_ever_offline    0
customer_value_total_ever_online     0
interested_in_categories_12          0
dtype: int64

##################### Quantiles #####################

                                   0.00  0.05   0.25   0.50   0.75    0.95    0.99     1.00
order_num_total_ever_online        1.00  1.00   1.00   2.00   4.00   10.00   20.00   200.00
order_num_total_ever_offline       1.00  1.00   1.00   1.00   2.00    4.00    7.00   109.00
customer_value_total_ever_offline 10.00 39.99  99.99 179.98 319.97  694.22 1219.95 18119.14
customer_value_total_ever_online  12.99 63.99 149.98 286.46 578.44 1556.73 3143.81 45220.13

In [30]:
# Distribution of the number of customers in shopping channels, total number of products purchased and total expenditures:
df.groupby("order_channel").agg({"master_id":"count",
                                 "order_num_total":"sum",
                                 "customer_value_total":"sum"})

               master_id  order_num_total  customer_value_total
order_channel
Android App         9495         52269.00            7819062.76
Desktop             2735         10920.00            1610321.46
Ios App             2833         15351.00            2525999.93
Mobile              4882         21679.00            3028183.16

In [32]:
# Top 5 customers with the most profits:
df.sort_values("customer_value_total", ascending=False)[:5]

                                  master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online                   interested_in_categories_12  order_num_total  customer_value_total
11150  5d1c466a-9cfd-11e9-9897-000d3a38a36f   Android App            Desktop       2013-10-11      2021-04-30             2021-04-30              2020-12-24                       200.00                          2.00                             684.97                          45220.13  [AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]           202.00              45905.10
4315   d5ef8058-a5c6-11e9-a2fc-000d3a38a36f   Android App        Android App       2018-08-06      2021-02-23             2021-02-23              2020-07-06                        67.00                          1.00                             130.49                          36687.80         [AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]            68.00              36818.29
7613   73fd19aa-9e37-11e9-9897-000d3a38a36f       Ios App            Offline       2014-01-14      2021-05-18             2021-01-30              2021-05-18                        81.00                          1.00                            1263.76                          32654.34              [ERKEK, COCUK, KADIN, AKTIFSPOR]            82.00              33918.10
13880  7137a5c0-7aad-11ea-8f20-000d3a38a36f       Ios App            Offline       2021-03-01      2021-04-13             2021-03-18              2021-04-13                        10.00                          1.00                             538.94                          30688.47                     [ERKEK, KADIN, AKTIFSPOR]            11.00              31227.41
9055   47a642fe-975b-11eb-8c2a-000d3a38a36f   Android App            Offline       2021-04-07      2021-04-27             2021-04-07              2021-04-27                         1.00                          3.00                           18119.14                           2587.20                                   [AKTIFSPOR]             4.00              20706.34

In [33]:
# Top 5 customers with the most orders:
df.sort_values("order_num_total", ascending=False)[:5]

                                  master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online                   interested_in_categories_12  order_num_total  customer_value_total
11150  5d1c466a-9cfd-11e9-9897-000d3a38a36f   Android App            Desktop       2013-10-11      2021-04-30             2021-04-30              2020-12-24                       200.00                          2.00                             684.97                          45220.13  [AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]           202.00              45905.10
7223   cba59206-9dd1-11e9-9897-000d3a38a36f   Android App        Android App       2013-02-21      2021-05-09             2021-05-09              2020-01-25                       130.00                          1.00                              49.99                          12232.25         [AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]           131.00              12282.24
8783   a57f4302-b1a8-11e9-89fa-000d3a38a36f   Android App            Offline       2019-08-07      2020-11-04             2020-09-07              2020-11-04                         2.00                        109.00                           10239.46                            143.98  [AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]           111.00              10383.44
2619   fdbe8304-a7ab-11e9-a2fc-000d3a38a36f   Android App            Offline       2018-10-18      2020-06-30             2018-10-18              2020-06-30                         1.00                         87.00                            8432.25                            139.98                                       [ERKEK]            88.00               8572.23
6322   329968c6-a0e2-11e9-a2fc-000d3a38a36f       Ios App            Ios App       2019-02-14      2021-04-05             2021-04-05              2020-02-17                         2.00                         81.00                            3997.55                            242.81                                       [ERKEK]            83.00               4240.36

## Calculating RFM Scores and Creating RFM Metrics and Segments

In [34]:
def create_rfm(dataframe):
    # Data Preperation
    dataframe["order_num_total"] = dataframe["order_num_total_ever_online"] + dataframe["order_num_total_ever_offline"]
    dataframe["customer_value_total"] = dataframe["customer_value_total_ever_offline"] + dataframe["customer_value_total_ever_online"]
    date_columns = dataframe.columns[dataframe.columns.str.contains("date")]
    dataframe[date_columns] = dataframe[date_columns].apply(pd.to_datetime)


    # Defining RFM Metrics
    dataframe["last_order_date"].max()  # 2021-05-30
    analysis_date = dt.datetime(2021, 6, 1)
    rfm = pd.DataFrame()
    rfm["customer_id"] = dataframe["master_id"]
    rfm["recency"] = (analysis_date - dataframe["last_order_date"]).astype('timedelta64[D]')
    rfm["frequency"] = dataframe["order_num_total"]
    rfm["monetary"] = dataframe["customer_value_total"]

    # Calculating RFM Scores
    rfm["recency_score"] = pd.qcut(rfm['recency'], 5, labels=[5, 4, 3, 2, 1])
    rfm["frequency_score"] = pd.qcut(rfm['frequency'].rank(method="first"), 5, labels=[1, 2, 3, 4, 5])
    rfm["monetary_score"] = pd.qcut(rfm['monetary'], 5, labels=[1, 2, 3, 4, 5])
    rfm["RF_SCORE"] = (rfm['recency_score'].astype(str) + rfm['frequency_score'].astype(str))
    rfm["RFM_SCORE"] = (rfm['recency_score'].astype(str) + rfm['frequency_score'].astype(str) + rfm['monetary_score'].astype(str))


    # Creating Segments with RFM Metrics and Scores
    seg_map = {
        r'[1-2][1-2]': 'hibernating',
        r'[1-2][3-4]': 'at_Risk',
        r'[1-2]5': 'cant_loose',
        r'3[1-2]': 'about_to_sleep',
        r'33': 'need_attention',
        r'[3-4][4-5]': 'loyal_customers',
        r'41': 'promising',
        r'51': 'new_customers',
        r'[4-5][2-3]': 'potential_loyalists',
        r'5[4-5]': 'champions'
    }
    rfm['segment'] = rfm['RF_SCORE'].replace(seg_map, regex=True)

    return rfm[["customer_id", "recency","frequency","monetary","RF_SCORE","RFM_SCORE","segment"]]

rfm_df = create_rfm(df)

In [35]:
rfm_df.head()

                            customer_id  recency  frequency  monetary RF_SCORE RFM_SCORE          segment
0  cc294636-19f0-11eb-8d74-000d3a38a36f    95.00       5.00    939.37       34       344  loyal_customers
1  f431bd5a-ab7b-11e9-a2fc-000d3a38a36f   105.00      21.00   2013.55       35       355  loyal_customers
2  69b69676-1a40-11ea-941b-000d3a38a36f   186.00       5.00    585.32       24       243          at_Risk
3  1854e56c-491f-11eb-806e-000d3a38a36f   135.00       2.00    121.97       31       311   about_to_sleep
4  d6ea1074-f1f5-11e9-9346-000d3a38a36f    86.00       2.00    209.98       31       311   about_to_sleep

## RFM Analysis

Examination of the recency, frequency and monetary averages of the segments:

In [38]:
rfm_df[["segment", "recency", "frequency", "monetary"]].groupby("segment").agg(["mean", "count"])

                    recency       frequency       monetary
                       mean count      mean count     mean count
segment
about_to_sleep       113.79  1629      2.40  1629   359.01  1629
at_Risk              241.61  3131      4.47  3131   646.61  3131
cant_loose           235.44  1200     10.70  1200  1474.47  1200
champions             17.11  1932      8.93  1932  1406.63  1932
hibernating          247.95  3604      2.39  3604   366.27  3604
loyal_customers       82.59  3361      8.37  3361  1216.82  3361
need_attention       113.83   823      3.73   823   562.14   823
new_customers         17.92   680      2.00   680   339.96   680
potential_loyalists   37.16  2938      3.30  2938   533.18  2938
promising             58.92   647      2.00   647   335.67   647

FLO includes a new women's shoe brand. The product prices of the brand it includes are above the general customer preferences. For this reason, it is desired to contact the customers in the target profile specifically for the promotion of the brand and product sales. These customers were planned to be loyal and female shoppers. ID numbers of relevant customers:

In [41]:
target_segments_customer_ids = rfm_df[rfm_df["segment"].isin(["champions","loyal_customers"])]["customer_id"]
cust_ids = df[(df["master_id"].isin(target_segments_customer_ids)) &(df["interested_in_categories_12"].str.contains("KADIN"))]["master_id"]
cust_ids.head()

0     cc294636-19f0-11eb-8d74-000d3a38a36f
1     f431bd5a-ab7b-11e9-a2fc-000d3a38a36f
8     cfbda69e-5b4f-11ea-aca7-000d3a38a36f
11    c2e15af2-9eed-11e9-9897-000d3a38a36f
33    fb840306-1219-11ea-a001-000d3a38a36f
Name: master_id, dtype: object

Up to 40% discount is planned for Men's and Children's products. We want to specifically target customers who are interested in the categories related to this discount, who are loyal customers in the past but have not shopped for a long time, and new customers. IDs of Customers in the appropriate profile:

In [45]:
target_segments_customer_ids = rfm_df[rfm_df["segment"].isin(["cant_loose","hibernating","new_customers"])]["customer_id"]
cust_ids = df[(df["master_id"].isin(target_segments_customer_ids)) & ((df["interested_in_categories_12"].str.contains("ERKEK"))|(df["interested_in_categories_12"].str.contains("COCUK")))]["master_id"]
cust_ids.head()

7     3f1b4dc8-8a7d-11ea-8ec0-000d3a38a36f
10    ae608ece-c9d8-11ea-a31e-000d3a38a36f
15    13ed97a4-b167-11e9-89fa-000d3a38a36f
19    2730793e-3908-11ea-85d6-000d3a38a36f
21    7b289956-d691-11e9-93bc-000d3a38a36f
Name: master_id, dtype: object